In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from patsy import dmatrices
from sklearn.decomposition import PCA
import numpy as np
from statsmodels.api import add_constant
from statsmodels.stats.outliers_influence import variance_inflation_factor
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler


#-*- coding : utf-8 -*-
# coding: utf-8#%%
plt.rcParams['axes.unicode_minus'] = False
df = pd.DataFrame(pd.read_csv('iris_training.csv', encoding='gbk'))
df


花萼长度  花萼宽度  花瓣长度  花瓣宽度  花种类
0     6.4   2.8   5.6   2.2    2
1     5.0   2.3   3.3   1.0    1
2     4.9   2.5   4.5   1.7    2
3     4.9   3.1   1.5   0.1    0
4     5.7   3.8   1.7   0.3    0
..    ...   ...   ...   ...  ...
115   5.5   2.6   4.4   1.2    1
116   5.7   3.0   4.2   1.2    1
117   4.4   2.9   1.4   0.2    0
118   4.8   3.0   1.4   0.1    0
119   5.5   2.4   3.7   1.0    1

[120 rows x 5 columns]

In [2]:
a=df.drop('花种类',axis=1)
a= StandardScaler().fit_transform(a)



In [3]:
a=PCA().fit(a)
a.explained_variance_

array([2.91275908, 0.95643143, 0.14364962, 0.02077332])

In [4]:
a.explained_variance_ratio_

array([0.72212152, 0.23711529, 0.03561314, 0.00515005])

In [5]:
a.components_

array([[ 0.52812682, -0.23873991,  0.58374863,  0.56861486],
       [ 0.35335532,  0.93387014,  0.0094546 ,  0.05419582],
       [-0.72269655,  0.23518019,  0.12967386,  0.6368553 ],
       [-0.27190401,  0.12482023,  0.80145669, -0.51783713]])

In [5]:
a.explained_variance_ratio_
